export const mockData = [
  {
    image: "../img/verstappen.png",
    driver: "Max Verstappen",
    team: "Oracle Red Bull Racing",
    nationality: "Paises Bajos",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/perez.png",
    driver: "Sergio Perez",
    team: "Oracle Red Bull Racing",
    nationality: "Mexico",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/hamilton.png",
    driver: "Lewis Hamilton",
    team: "Mercedes-AMG F1 Team",
    nationality: "Reino Unido",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/russell.png",
    driver: "George Russell",
    team: "Mercedes-AMG F1 Team",
    nationality: "Reino Unido",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/alonso.png",
    driver: "Fernando Alonso",
    team: "Aston Martin",
    nationality: "España",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/stroll.png",
    driver: "Lance Stroll",
    team: "Aston Martin",
    nationality: "Canada",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/leclerc.png",
    driver: "Charles Leclerc",
    team: "Scuderia Ferrari",
    nationality: "Monaco",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/sainz.png",
    driver: "Carlos Sainz",
    team: "Scuderia Ferrari",
    nationality: "España",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/tsunoda.png",
    driver: "Yuki Tsunoda",
    team: "Scuderia AlphaTauri",
    nationality: "Japón",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/devries.png",
    driver: "Nick De Vries",
    team: "Scuderia AlphaTauri",
    nationality: "Paises Bajos",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/bottas.png",
    driver: "Valteri Bottas",
    team: "Alfa Romeo F1 Team",
    nationality: "Finlandia",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/zhou.png",
    driver: "Guanyu Zhou",
    team: "Alfa Romeo F1 Team",
    nationality: "China",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/norris.png",
    driver: "Lando Norris",
    team: "McLaren F1 Team",
    nationality: "Reino Unido",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/piastri.png",
    driver: "Oscar Piastri",
    team: "McLaren F1 Team",
    nationality: "Australia",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/sargeant.png",
    driver: "Logan Sargeant",
    team: "Williams Racing",
    nationality: "EE.UU.",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/albon.png",
    driver: "Alex Albon",
    team: "Williams Racing",
    nationality: "Tailandia",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/hulkenberg.png",
    driver: "Nico Hulkenberg",
    team: "MoneyGram Haas F1 Team",
    nationality: "Alemania",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/magnussen.png",
    driver: "Kevin Magnussen",
    team: "MoneyGram Haas F1 Team",
    nationality: "Dinamarca",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/gasly.png",
    driver: "Pierre Gasly",
    team: "BWT Alpine F1 Team",
    nationality: "Francia",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
  {
    image: "../img/ocon.png",
    driver: "Esteban Ocon",
    team: "BWT Alpine F1 Team",
    nationality: "Francia",
    debutYear: "",
    oldTeams: [""],
    biography: "http://",
  },
];